type: rpm-ostree

install:
  - libreoffice
  - virt-install
  - libvirt-daemon-config-network
  - libvirt-daemon-kvm
  - qemu
  - qemu-kvm
  - virt-manager
  - virt-viewer

remove:
  - waydroid-selinux
  - waydroid
  - cage