name: kinoite-ekyso
description: This is my personal OS image.


base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - from-file: modules/rpm-ostree.yml
  - from-file: modules/default-flatpaks.yml
  - type: signing

